import {describe,it,expect} from "vitest";
import {AIBrain} from "../src/brain.js";
import type {AgentDefinition,ToolDefinition} from "../src/domain/types.js";
const agent=(authority:any=1,permissions:any[]=["read","write","execute"]):AgentDefinition=>({id:"sec",name:"sec",description:"sec",capabilities:["general"],permissions,authority,canHandle:t=>t.type==="goal"||t.type==="planned",async execute(){return{status:"completed",summary:"secure-test"}}});
const setup=(authority:any=1,permissions:any[]=["read","write","execute"])=>{const b=new AIBrain();const p=b.createProject("security");b.registerAgent(agent(authority,permissions));return{b,p};};
describe("100 adversarial security tests",()=>{
it("security-1",async()=>{const {b,p}=setup(1);expect((await b.request({projectId:p.id,goal:"x",permissions:["deploy-production"]})).status).toBe("blocked");});
it("security-2",async()=>{const {b,p}=setup(1);expect((await b.request({projectId:p.id,goal:"x",permissions:["deploy-staging"]})).status).toBe("blocked");});
it("security-3",async()=>{const {b,p}=setup(1);expect((await b.request({projectId:p.id,goal:"x",permissions:["financial"]})).status).toBe("blocked");});
it("security-4",async()=>{const {b,p}=setup(1);expect((await b.request({projectId:p.id,goal:"x",permissions:["legal"]})).status).toBe("blocked");});
it("security-5",async()=>{const {b,p}=setup(1);expect((await b.request({projectId:p.id,goal:"x",permissions:["destructive"]})).status).toBe("blocked");});
it("security-6",async()=>{const {b,p}=setup(1);expect((await b.request({projectId:p.id,goal:"x",permissions:["security-policy"]})).status).toBe("blocked");});
it("security-7",async()=>{const {b,p}=setup(6);expect((await b.request({projectId:p.id,goal:"x",risk:"critical"})).status).toBe("blocked");});
it("security-8",async()=>{const {b,p}=setup(6);b.stopAll();expect((await b.request({projectId:p.id,goal:"x"})).status).toBe("blocked");});
it("security-9",async()=>{const {b,p}=setup(6);b.stopAll();expect((await b.request({projectId:p.id,goal:"x",risk:"high"})).status).toBe("blocked");});
it("security-10",async()=>{const {b,p}=setup(6);b.stopAll();expect((await b.request({projectId:p.id,goal:"x",risk:"critical"})).status).toBe("blocked");});
it("security-11",async()=>{const {b}=setup();expect((await b.orchestrator.runTask("missing")).status).toBe("blocked");});
it("security-12",async()=>{const {b,p}=setup(6);await b.request({projectId:p.id,goal:"x",risk:"critical"});const t=[...b.store.tasks.values()][0]!;expect((await b.resumeApproved(t.id,"missing")).status).toBe("blocked");});
it("security-13",async()=>{const {b,p}=setup(6);await b.request({projectId:p.id,goal:"a",risk:"critical"});await b.request({projectId:p.id,goal:"b",risk:"critical"});const a=[...b.store.approvals.values()][0]!;const t=[...b.store.tasks.values()][1]!;expect((await b.resumeApproved(t.id,a.id)).status).toBe("blocked");});
it("security-14",async()=>{const {b,p}=setup(6);await b.request({projectId:p.id,goal:"x",risk:"critical"});const a=[...b.store.approvals.values()][0]!,t=[...b.store.tasks.values()][0]!;b.approvals.decide(a.id,"rejected","owner");expect((await b.resumeApproved(t.id,a.id)).status).toBe("blocked");});
it("security-15",async()=>{const {b,p}=setup(6);await b.request({projectId:p.id,goal:"x",risk:"critical"});const a=[...b.store.approvals.values()][0]!;b.approvals.decide(a.id,"approved","owner");expect(()=>b.approvals.decide(a.id,"approved","owner2")).toThrow();});
it("security-16",async()=>{const {b}=setup();const t:ToolDefinition={name:"x",description:"x",risk:"low",requiredPermissions:["read"],execute:async()=>1};b.tools.register(t);expect(()=>b.tools.register(t)).toThrow();});
it("security-17",async()=>{const {b,p}=setup();const a=agent();const t:any={id:"t",projectId:p.id,title:"t",description:"",type:"goal",status:"queued",dependencies:[],risk:"low",permissions:["read"],acceptanceCriteria:[],attempts:0,createdAt:"",updatedAt:""};b.store.tasks.set(t.id,t);await expect(b.tools.execute({taskId:t.id,agentId:a.id,toolName:"missing",permissions:[],taskPermissions:["read"],risk:"low",input:{}},a)).rejects.toThrow();});
it("security-18",async()=>{const {b}=setup(1,["read"]);b.tools.register({name:"w",description:"w",risk:"low",requiredPermissions:["write"],execute:async()=>1});expect(b.tools.allowedFor({permissions:["read"],risk:"low"} as any,agent(1,["read"]))).not.toContain("w");});
it("security-19",async()=>{const {b}=setup(6,["read","write","execute","destructive"]);b.tools.register({name:"c",description:"c",risk:"critical",requiredPermissions:["destructive"],execute:async()=>1});expect(b.tools.allowedFor({permissions:["destructive"],risk:"critical"} as any,agent(6,["destructive"]))).not.toContain("c");});
it("security-20",async()=>{const {b}=setup(6,["read","execute"]);b.tools.register({name:"h",description:"h",risk:"high",requiredPermissions:["execute"],execute:async()=>1});expect(b.tools.allowedFor({permissions:["execute"],risk:"low"} as any,agent(6,["execute"]))).not.toContain("h");});
it("security-21",async()=>{const {b,p}=setup();const t=b.plan(p.id,[{key:"x",title:"x",description:"x"}])[0]!;t.budget={maxAttempts:0};expect((await b.orchestrator.runTask(t.id)).status).toBe("blocked");});
it("security-22",async()=>{const {b,p}=setup();const t=b.plan(p.id,[{key:"a",title:"a",description:"a"},{key:"b",title:"b",description:"b",dependsOn:["a"]}]);t[0]!.status="failed";expect(b.taskGraph.ready(p.id)).toHaveLength(0);});
it("security-23",async()=>{const {b,p}=setup();const t=b.plan(p.id,[{key:"a",title:"a",description:"a"},{key:"b",title:"b",description:"b",dependsOn:["a"]}]);t[0]!.status="cancelled";expect(b.taskGraph.ready(p.id)).toHaveLength(0);});
it("security-24",async()=>{const {b,p}=setup();expect(()=>b.plan(p.id,[{key:"a",title:"a",description:"a",dependsOn:["a"]}])).toThrow();});
it("security-25",async()=>{const {b,p}=setup();expect(()=>b.plan(p.id,[{key:"a",title:"a",description:"a"},{key:"a",title:"b",description:"b"}])).toThrow();});
it("security-26",async()=>{const {b,p}=setup();expect(()=>b.plan(p.id,[{key:"a",title:"a",description:"a",dependsOn:["missing"]}])).toThrow();});
it("security-27",async()=>{const {b,p}=setup();const m=b.remember({projectId:p.id,type:"rule",content:"old",tags:["x"],source:"x",confidence:1,importance:1});b.supersedeMemory(m.id,{projectId:p.id,type:"rule",content:"new",tags:["x"],source:"x",confidence:1,importance:1});expect(b.memory.retrieve(p.id,"x")).toHaveLength(1);expect(b.memory.retrieve(p.id,"x")[0]!.content).toBe("new");});
it("security-28",async()=>{const {b,p}=setup();const q=b.createProject("other");b.remember({projectId:q.id,type:"fact",content:"secret",tags:["secret"],source:"x",confidence:1,importance:10});expect(b.memory.retrieve(p.id,"secret")).toHaveLength(0);});
it("security-29",async()=>{const {b,p}=setup();b.remember({type:"fact",content:"global",tags:["global"],source:"x",confidence:1,importance:1});expect(b.memory.retrieve(p.id,"global")).toHaveLength(1);});
it("security-30",async()=>{const {b,p}=setup();await b.request({projectId:p.id,goal:"x"});const t=[...b.store.tasks.values()][0]!;expect((await b.resumeApproved(t.id,"")).status).toBe("blocked");});
it("security-31",async()=>{const {b,p}=setup();await b.request({projectId:p.id,goal:"x"});const t=[...b.store.tasks.values()][0]!;expect((await b.resumeApproved(t.id,"bad")).status).toBe("blocked");});
it("security-32",async()=>{const {b,p}=setup();await b.request({projectId:p.id,goal:"x",risk:"critical"});const a=[...b.store.approvals.values()][0]!;expect(a.taskId).toBe([...b.store.tasks.values()][0]!.id);});
it("security-33",async()=>{const {b,p}=setup();await b.request({projectId:p.id,goal:"x"});expect(b.store.events.every(e=>e.id.length>0)).toBe(true);});
it("security-34",async()=>{const {b,p}=setup();b.tools.register({name:"w",description:"w",risk:"low",requiredPermissions:["write"],execute:async()=>1});const a=agent(1,["read"]);const t:any={id:"t",projectId:p.id,title:"t",description:"",type:"goal",status:"queued",dependencies:[],risk:"low",permissions:["read"],acceptanceCriteria:[],attempts:0,createdAt:"",updatedAt:""};b.store.tasks.set(t.id,t);await expect(b.tools.execute({taskId:t.id,agentId:a.id,toolName:"w",permissions:[],taskPermissions:["read"],risk:"low",input:{}},a)).rejects.toThrow();expect(b.store.events.some(e=>e.type==="tool.blocked")).toBe(true);});
it("security-35",async()=>{const {b,p}=setup(6,[]);expect((await b.request({projectId:p.id,goal:"x",permissions:["write"]})).status).toBe("blocked");});
it("security-36",async()=>{const {b,p}=setup(-1,[]);expect((await b.request({projectId:p.id,goal:"x"})).status).toBe("blocked");});
it("security-37",async()=>{const {b,p}=setup(6);expect((await b.request({projectId:p.id,goal:"x",permissions:["destructive"]})).status).toBe("blocked");});
it("security-38",async()=>{const {b,p}=setup(6);expect((await b.request({projectId:p.id,goal:"x",risk:"critical",permissions:["read"]})).status).toBe("blocked");});
it("security-39",async()=>{const {b,p}=setup(6);await b.request({projectId:p.id,goal:"x",risk:"critical"});const t=[...b.store.tasks.values()][0]!,a=[...b.store.approvals.values()][0]!;b.approvals.decide(a.id,"approved","owner");await b.resumeApproved(t.id,a.id);expect(t.id).toBe(a.taskId);});
it("security-40",async()=>{const {b}=setup();expect(b.policy.isStopped()).toBe(false);b.stopAll();expect(b.policy.isStopped()).toBe(true);b.resume();expect(b.policy.isStopped()).toBe(false);});
it("security-41",async()=>{const {b,p}=setup(0,["read"]);b.tools.register({name:"r",description:"r",risk:"low",requiredPermissions:["read"],execute:async()=>42});const t:any={id:"r1",projectId:p.id,title:"r",description:"",type:"goal",status:"queued",dependencies:[],risk:"low",permissions:["read"],acceptanceCriteria:[],attempts:0,createdAt:"",updatedAt:""};b.store.tasks.set(t.id,t);expect(await b.tools.execute({taskId:t.id,agentId:"a",toolName:"r",permissions:[],taskPermissions:["read"],risk:"low",input:{}},agent(0,["read"]))).toBe(42);});
it("security-42-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-43-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-44-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-45-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-46-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-47-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-48-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-49-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-50-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-51-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-52-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-53-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-54-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-55-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-56-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-57-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-58-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-59-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-60-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-61-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-62-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-63-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-64-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-65-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-66-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-67-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-68-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-69-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-70-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-71-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-72-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-73-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-74-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-75-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-76-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-77-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-78-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-79-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-80-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-81-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-82-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-83-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-84-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-85-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-86-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-87-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-88-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-89-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-90-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-91-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-92-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-93-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-94-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-95-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-96-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-97-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-98-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-99-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
it("security-100-isolation-boundary",()=>{const {b,p}=setup();expect(p.id).toBeTruthy();expect(b.store.projectTasks(p.id)).toHaveLength(0);expect(b.store.events).toHaveLength(0);});
});